[package]
name = "libmalinstrack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.148"
sqlite = "0.31.1"

[lib]
name         = "malinstrack"
crate-type   = ["rlib", "cdylib"]
